{{- if .Values.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:  
  name: {{ template "chartmuseum-ui.name" . }}-vars
data:
  {{- range $key, $value := .Values.envVars }}
  {{ $key }}: {{ tpl ($value | quote) $ }}
  {{- end }}
{{- end }}