{{- if .Values.enabled }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chartmuseum-ui
  labels:
    app: {{ template "chartmuseum-ui.name" . }}
    chart: {{ template "chartmuseum-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: chartmuseum-ui
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      initContainers:
      - name: verify-dependencies
        image: busybox
        command: ['sh', '-c', 'until wget -q {{ .Values.envVars.CHART_MUSESUM_URL }} -o /dev/null; do echo waiting for chartmuseum backend...; sleep 2; done']
      containers:
      - name: chartmuseum-ui
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: {{ template "chartmuseum-ui.name" . }}-vars
{{- end }}
