{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: chartmuseum-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "chartmuseum-ui.name" . }}
    chart: {{ template "chartmuseum-ui.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
  - name: chartmuseum-ui
    protocol: TCP
    port: 8080
  selector:
    app: chartmuseum-ui
{{- end }}