{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: chartmuseum-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "chartmuseum-ui.name" . }}
    chart: {{ template "chartmuseum-ui.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "chartmuseum-ui.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}