enabled: true

replicaCount: 1
image:
  repository: idobry/chartmuseumui
  tag: latest

ingress:
  enabled: false
  hosts:
    - chartmuseum-ui.local
  annotations: {}
    # kubernetes.io/ingress.class: nginx

nodeSelector: {}
tolerations: []
podAnnotations: {}

chartmuseumURL: chartmuseum.kube-system.svc.cluster.local