enabled: true

replicaCount: 1
image:
  repository: idobry/chartmuseumui
  tag: latest

ingress:
  enabled: true
  hosts:
    - chartmuseum-ui.local
  annotations: {}
    # kubernetes.io/ingress.class: nginx

nodeSelector: {}
tolerations: []
podAnnotations: {}

service:
  type: ClusterIP
  port: 8080

envVars:
  CHART_MUSESUM_URL: "http://chartmuseum.svc.cluster.local"
  CHART_MUSESUM_API_GET_CHARTS:
  BASIC_AUTH_USERS: '[{"username":"admin", "password":"password"}, {"username":"user", "password":"s3cr3t"}]'