enabled: true

replicaCount: 1
image:
  repository: idobry/chartmuseumui
  tag: latest

ingress:
  enabled: true
  hosts:
    - chartmuseum-ui.local
  annotations: {}
    # kubernetes.io/ingress.class: nginx

nodeSelector: {}
tolerations: []
podAnnotations: {}

service:
  type: ClusterIP
  port: 8080

chartmuseumURL: "http://chartmuseum.svc.cluster.local"